dankogai/p5-encode

lib/Encode/MIME/Header.pm
t/taint.t

On perl 5.8.8 and below, loading utf8_heavy.pl (which happens implictly
in many places) will cause a split using a character class to not
maintain the taint flag.  Since the MIME header encoding reconstructs
the string after splitting it, we need to explicitly copy the taint flag
using a substr($s, 0, 0).
Also includes a small test adjustment I used to track this down.

maintain taint flag when encoding MIME on old perl

---

Encode.xs
bin/enc2xs

NOTE: This PR will fix https://rt.cpan.org/Ticket/Display.html?id=82897
The change to enc2xs follows from this thread:
http://www.nntp.perl.org/group/perl.perl5.porters/2015/01/msg224875.html
The change to Encode.xs is to fix errors in the Encode.c compilation
which results from the enc2xs change (now that we specify "C" linkage, the
header file cannot be #included within { }):
c:\dev\git\perl\cpan\encode\def_t.h(7) : error C2598: linkage specification must be at global scope
c:\dev\git\perl\cpan\encode\def_t.h(7) : error C2512: 'encode_s' : no appropriate default constructor available
c:\dev\git\perl\cpan\encode\def_t.h(8) : error C2598: linkage specification must be at global scope
c:\dev\git\perl\cpan\encode\def_t.h(8) : error C2512: 'encode_s' : no appropriate default constructor …

Fix C++ build on Windows with VC++

---

Unicode/Unicode.pm

This $VERSION bump is necessary to keep bleadperl's
Porting/cmpVERSION.pl script happy when comparing current blead against
perl-5.20.1. blead has Encode-2.68; 5.20.1 has Encode-2.60. This module has
changed (in its XS file *), but its $VERSION number has not.
(*) It's a tiny, insignicificant change--not even a change in
documentation, let alone in functionality--but the cmpVERSION.pl script
doesn't understand that. It simply requires that different versions of a
file have different $VERSION numbers.

Bump $VERSION in module changed since Encode-2.60

---

MANIFEST
bin/encguess

Added the CLI wrapper for Encode::Guess as suggested in ticket Rt98660:
https://rt.cpan.org/Ticket/Display.html?id=98660
Wasn't sure if this needed to be referenced in the Makefile.PL, so I left it as is.

Rt98660 Added CLI wrapper for Encode::Guess

---

.gitignore

Currently, git users have to remember to avoid accidentally checking in files generated by make. I've added a basic list of these file patterns to our `.gitignore`.
In the future, we should probably build all artifacts into a `target/` directory or similar.

gitignore build artifacts

---

encoding.pm

See
http://perl5.git.perl.org/perl.git/commit/3e669301f0a6fa34269f0e1eaf1fbbd72cae498a
and https://rt.cpan.org/Public/Bug/Display.html?id=100347
encoding needs to be lexically scoped to prevent conflicts between code.
Since November, this patch has been in blead, and all (the few) problems
encountered fixed.  As we approach v5.22, this patch should be applied
to Encode,  See
<CADED=K5eFj_tCRuOsfJDsqJdTXDQYwJB5-14TqojCpS6DaDDiA@mail.gmail.com>

Sync encoding.pm with blead

---

encoding.pm

On an EBCDIC platform, if someone specifies 'no encoding' it croaks at
compile time.  But it isn't a problem to specify 'no encoding'.  It is
only a problem to specify 'use encoding'.  So move the test to the
import function.

Encode::encoding: Don't fail 'no encoding' on EBCDIC

---

encoding.pm

Move some checks as constants to allow perl to inline more at cxompile time:
- HAS_PERLIO check
- perl 5.21.7 check

encoding.pm: more inlining

---

encoding.pm
t/encoding-locale.t

The current version of `encoding::_get_locale_encoding` returns `undef` **on Win32**. The consequence is that `use open ':locale', ':std'` doesn't work on this platform.
Demo:
```
perl -mencoding -E "say encoding::_get_locale_encoding"
wperl -mencoding -MWin32 -E "Win32::MsgBox('['.encoding::_get_locale_encoding.']')"
```
This patch fixes this issue by using `GetOutputCP()` / `GetACP()` depending on wether we are in a console program or an GUI program.
By the way, the rewrite **also affects Unix platforms to have a more portable solution**: we now use `I18N::Langinfo::langinfo(CODESET)` to retrieve the code page instead of guessing it just from the locale name. And in case of fallback to the locale name, we use `POSIX::setlocale` to retrieve the locale name instead of directly using …

Rewrite of encoding::_get_locale_encoding for more portability

---

MANIFEST

In #40 I had submitted a new test file, `t/encoding-locale.t`. Unfortunately I did not notice that MANIFEST had to be manually updated. So this test never reached CPAN.
Let's push it to the world!

MANIFEST: add missing t/encoding-locale.t

---

t/encoding-locale.t

On our HP-UX systems, _get_locale_encoding returns undef. This caused the encoding-locale test to fail with the following output:
```1..3
ok 1 - _get_locale_encoding returns a scalar value
Use of uninitialized value $name in substitution (s///) at blib/lib/Encode.pm line 103.
Use of uninitialized value $name in exists at blib/lib/Encode.pm line 106.
Use of uninitialized value $name in lc at blib/lib/Encode.pm line 107.
Use of uninitialized value $find in exists at blib/lib/Encode/Alias.pm line 25.
Use of uninitialized value $find in hash element at blib/lib/Encode/Alias.pm line 26.
Use of uninitialized value $find in pattern match (m//) at blib/lib/Encode/Alias.pm line 31.
Use of uninitialized value $find in lc at blib/lib/Encode/Alias.pm line 40.
Use of uninitialized value $find in …
```

Fix the encoding-locale test to skip properly if _get_locale_encoding returns undef

---

Encode.pm

This patch adds a few lines in the docs for encode(), decode() and decode_utf8() to make it explicit to the reader that their inputs might be at risk of being modified.
This information is already contained in the docs, although it's a bit easy to overlook it; the goal of the patch is to make anyone reading the docs for one of those functions immediately aware that their inputs might be at risk unless proper actions are taken.

In-place modifications made explicit in docs for encode(), decode() and decode_utf8() 

---

Makefile.PL

Environment:
* Perl 5.8.8 and Test::More@0.62
Error message:
```
...
t/encoding-locale..........Undefined subroutine &main::note called at t/encoding-locale.t line 25.
dubious
Test returned status 255 (wstat 65280, 0xff00)
after all the subtests completed successfully
...
```
Test::More@0.80 or before does not have note() method.
https://metacpan.org/changes/distribution/Test-Simple
```
...
0.81_01  Sat Sep  6 15:13:50 PDT 2008
New Features
* Adam Kennedy bribed me to add new_ok().  The price was one DEFCON license key.
[rt.cpan.org 8891]
* TODO tests can now start and end with 'todo_start' and 'todo_end'
Test::Builder methods. [rt.cpan.org 38018]
* Added Test::Builder->in_todo() for a safe way to check if a test is inside a
TODO block.  This allows TODO tests with no reason.
* Added …
```

t/encoding-locale.t fails with Test::More@0.80 or before.

---

Encode.pm
t/utf8warnings.t

This applies the same changes in a6c2ba38 (pull #26) to the `from_to`
method as well.

Rethrow 'utf8' warnings in from_to as well

---

Encode.pm
bin/enc2xs
bin/encguess
bin/piconv
bin/ucmlint
bin/unidump

The change to Encode.pm is the most critical part of this patch.
Without this change, and process that uses Encode started with a
current directory that's world writable (such as /tmp) and if there's
no global Encode::ConfigLocal, can be attacked by another user
by creating /tmp/Encode/ConfigLocal.pm
It's possible most of the tools changed here do not need to be updated,
but I chose a conservative path.

CVE-2016-1238: avoid loading optional modules from .

---

Encode.xs
encoding.pm

These changes are sufficient for me to get things rolling on older perls. I **have not** used `Devel::PPPort` as it does not seem to work cleanly (likely conflicts with preexisting macro definitions deep in `Encode`'s source, perhaps something @wolfsage can answer better).
The PR is the best I can do given my current know-how, feel free to reject it and implement something better!
Cheers

Fixes for 5.8.x compilation failures

---

Encode.pm
t/utf8ref.t

Documentation says that '$octets = encode_utf8($string)' is equivalent to
'$octets = encode("utf8", $string)'. And if the $string is undef, then
undef is returned. However without this patch encode_utf8(undef) returned
'' (empty string) and not undef. This patch fixes it and undef is returned.
All other utf8 Encode calls already returns undef, just encode_utf8() acted
differently.
Encode::encode('utf8', undef) -> undef
Encode::decode('utf8', undef) -> undef
Encode::decode_utf8(undef) -> undef
Reported bug: https://rt.cpan.org/Public/Bug/Display.html?id=116904

Fix return value of Encode::encode_utf8(undef)

---

Encode.xs
t/fallback.t
t/utf8strict.t

Support for EBCDIC was not tested + test cases are missing.

Encode::utf8: Fix processing invalid UTF-8 subsequences

---

Encode.xs

This revert back previous behavior. See comment: https://github.com/dankogai/p5-encode/issues/64#issuecomment-240656967

Encode::utf8: Fix count of replacement characters for overflowed and overlong UTF-8 sequences

---

lib/Encode/Encoder.pm
t/undef.t

This pull request will fix the "panic: sv_setpvn called with negative strlen at /usr/lib/perl5/5.8.8/i386-linux-thread-multi/Encode/Encoder.pm line 84" error, when you will try to Encoder::encode a undefined scalar. See also the accompanied unit test (t/undef.t).

Fix panic when encoding undef scalars

---

Encode.xs
MANIFEST
lib/Encode/CN/HZ.pm
lib/Encode/Encoder.pm
t/decode.t
t/magic.t
t/rt85489.t
t/utf8ref.t

Before this patch every function XS function did it differently and not
every one correctly. Now SvPV_force_nomg() is used when source argument
is going to be modified. SvGETMAGIC() is called when entering into
functions and then only "nomg" variants of perl functions are used to
prevent processing get magic more times. SvSETMAGIC() is called after
modification of source argument.
This fixes bugs:
https://rt.cpan.org/Public/Bug/Display.html?id=117158
https://rt.cpan.org/Public/Bug/Display.html?id=85489
https://github.com/dankogai/p5-encode/pull/66
See discussion about this patch, Father Chrysostomos reviewed it:
http://code.activestate.com/lists/perl5-porters/233137/
http://www.nntp.perl.org/group/perl.perl5.porters/2016/10/msg240511.html
---
Now magic scalars should be handled correctly …

Fix handling of undef, ref, typeglob, UTF8, COW and magic scalar argument in all XS functions

---

Encode.xs
MANIFEST
t/rt113164.t

Construction like this:
ST(0) = encode_method(aTHX_ enc, enc->f_utf8, src, check, NULL, Nullsv, NULL, fallback_cb);
with src = ST(1) and fallback_cb as subroutine which reallocate perl stack
leads to undefined behaviour when pointers to perl stack variables are
modified more times between two sequence points.
When that code is compiled under gcc 4.6 then at first is evaluated pointer
for ST(0), second is evaluation of encode_method() function and third is
assignment of return value. But encode_method() modified pointers to perl
stack variables and old pointer for ST(0) from first step does not have to
be correct...
With this patch ST(0) is not directly modified between two sequence points
but via temporary variable RETVAL. Tested under valgrind that memory
corruption disappeared.
Fixes …

Fix crash caused by undefined behaviour between two sequence points

---

Encode.xs
t/taint.t

Encode documentation says:
For security reasons, this function does not work on tainted values.

Disable _utf8_on and _utf8_off for tainted values

---

Encode.xs
Unicode/Unicode.xs

All those macros evaluates it arguments more times, so it is not safe to
pass expressions into them. Instead store intermediate result in temporary
variable and pass that temporary variable into those macros.
Fixes: https://rt.cpan.org/Public/Bug/Display.html?id=82348

Do not use expressions in macros SvTRUE, SvPV, SvIV, attr and attr_true

---

Encode.xs
Unicode/Unicode.xs

C++11 changed from earlier versions to require space between the end of
a string literal and a macro, so that a feature can unambiguously be
added to the language.  Starting in g++ 6.2, the compiler emits a
deprecation warning when there isn't a space (presumably so that future
versions can support C++11).
Although not required by the C++11 change, this patch also makes sure
there is space after a macro call, before a string literal.  This makes
the macro stand out, and is easier to read.
Code and modules included with the Perl core need to be compilable using
C++.  This is so that perl can be embedded in C++ programs. (Actually,
only the hdr files need to be so compilable, but it would be hard to
test that just the hdrs are compilable.)  So we need to accommodate
changes to the C++ …

Encode: Rmv impediment to compiling under C++11

---

t/mime-header.t

We need to decrease string length, because such long strings cause stack
growth failure and SIGSEGV.

Fix test t/mime-header.t to pass on HP-UX 11.23/64 U with perl v5.8.3

---

t/taint.t

Encode::ConfigLocal can load additional encodings which are not part of
Encode distribution and which can be buggy (namely Encode::IBM and
Encode::IMAPUTF7). This fix restore original set of encodings which are
part of Encode only.
Fixes: https://rt.cpan.org/Public/Bug/Display.html?id=103896

Fix test t/taint.t to pass when Encode::ConfigLocal is present

---

Encode.xs
t/fallback.t
t/truncated_utf8.t

When truncated UTF-8 sequence was followed by another truncated UTF-8
sequence optionally followed by UTF-8 invariant at the end of string and
first sequence in case it would have been not-truncated is longer as
current string then the whole sequence was replaced just by one Unicode
replacement characters, instead of two (for each invalid/truncated UTF-8
sequence).
This happened also in case Encode was called with STOP_AT_PARTIAL flag.

Fix appending correct number of Unicode replacement characters

---

t/truncated_utf8.t

Set failure_output fd and todo_output fd as ":utf8" because error message
contains wide characters.

Fix t/truncated_utf8.t test warning: Wide character in print at Test/Builder.pm

---

t/whatwg-aliases.json
t/whatwg-aliases.t

The WHATWG has an [Encoding Living Standard](https://encoding.spec.whatwg.org/).
The list of encodings and aliases in that specification is also available as [a JSON file](https://encoding.spec.whatwg.org/encodings.json).
I wrote a test that check Encode's list of encoding against this JSON. 
Many failures are reported. It is beyond my knowledge how each failure has to be fixed, so I'm submitting the testsuite 'as is'.
To run the test:
```
AUTHOR_TESTING=1 prove -l t/whatwg-aliases.t
```

New (failing) tests for aliases defined in WHATWG Encoding spec

---

lib/Encode/CN/HZ.pm
lib/Encode/GSM0338.pm
lib/Encode/JP/JIS7.pm
lib/Encode/KR/2022_KR.pm
lib/Encode/MIME/Header.pm
lib/Encode/MIME/Header/ISO_2022_JP.pm
lib/Encode/Unicode/UTF7.pm
t/undef.t

Currently encode and decode methods of more Encode modules returned empty
string for input undef values. This patches fixes it and now both calls
Encode::find_encoding($enc)->encode(undef);
Encode::encode($enc, undef);
are equivalent and return undef. Same for decode().
Unit test t/undef.t was extended to verify this state.

Fix all Encode modules so their encode(undef) and decode(undef) calls returns undef

---

Encode.xs

newSVnv() created scalar with floating point value from unsigned integer
which could loose precision. So use newSVuv() instead.

Call Encode callback function with integer argument correctly

---

Encode.pm

For more then 10 years fallback CHECK coderef for decode() must return
already decoded string and not octets. Returned value is really not later
decoded. So fix documentation and example about this fact.

Fix documentation about CHECK coderef

---

Encode.pm
Encode.xs
MANIFEST
t/enc_eucjp.t
t/enc_utf8.t
t/utf8messages.t

Two important changes in this pull request are:
**Encode::utf8: decode: Error message now contains original source sequence**:
* After this change error message for invalid UTF-8 sequence when decoding will contain original invalid sequence in hex format
* Before it was partially decoded Unicode codepoint
* Fallback coderef for decode will now contains in @_ arguments whole invalid UTF-8 sequence and not only first invalid byte
* https://rt.cpan.org/Public/Bug/Display.html?id=36348
**Encode::utf8: Error message in strict mode now contains "UTF-8"**:
* Before this patch in error message was "utf8" as name of encoding
* Now name in error message is chosen by strict mode, either "UTF-8" or "utf8"
And other two are:
**Encode::utf8: Remove defines for UTF8_ALLOW_STRICT and …

Fixes for Encode::utf8

---

Encode.xs
t/fallback.t

* Avoid magic number
* Initialize uv to safe value
* Fix memory leaks if the callback invoked in call_sv throws an exception
* Throw exception when encode callback returns wide multi-byte character
* Correctly handle scalar from callback regardless of UTF-8 upgradeness
* Fix a bug when downgraded Unicode codepoints between 128-255 from callback were decoded as UTF-8 bytes and upgraded Latin1 chars were also encoded as UTF-8 bytes

Cleanup code for handling fallback/replacement characters

---

Encode.xs
encoding.pm
t/enc_eucjp.t
t/enc_utf8.t

* With cperl encoding is not deprecated
* With cperl 5.27.0 there's a new strict hashpairs mode. https://github.com/perl11/cperl/issues/281

cperl fixes: encoding undeprecated, no strict hashpairs

---

t/truncated_utf8.t
t/utf8messages.t

* Skip tests on older Perl versions which cause infinite loop due to bug: https://rt.perl.org/Public/Bug/Display.html?id=41442
* Turn off t/utf8messages.t warnings which appears only with older Perl versions

Fixes for older perl versions

---

Encode.pm
Unicode/Unicode.pm
lib/Encode/Encoding.pm
lib/Encode/Guess.pm
lib/Encode/JP/JIS7.pm
lib/Encode/MIME/Header.pm
lib/Encode/MIME/Header/ISO_2022_JP.pm

Do not assign directly to hash $Encode::Encoding but rather use Encode::define_encoding(). This unify code for registering new encodings.
Correctly propagate carp() and croak() messages from Encode modules back to caller. Normally caller use Encode::encode() or Encode::decode() function and when Encode module throw carp() or croak() message, then Carp show information that it was called in Encode.pm instead real caller of Encode.
This patch properly fill CARP_NOT for skipping Encode, Encode::Encoder, Encode::Encoding and Encode modules so correct caller of Encode will be shown in carp() and croak() messages.
This patch also remove localization of $Carp::CarpLevel as it is not needed by this change anymore.

Use Encode::define_encoding and propagate carp/croak messages

---

Encode.pm
Encode.xs

By this change XS functions with prototypes are finally correctly exported. Encodings defined by XS code are now registered by new XS function onBOOT instead from XS BOOT code like described in XSLoader documentation.
Remove parenthesis around constant subs. They are not needed anymore as all XS functions are finally properly exported with defined prototypes.

Run Encode XS BOOT code at compile time

---

Encode.pm
Encode.xs
Unicode/Unicode.pm
Unicode/Unicode.xs

Encode does not work without XS for a long time, so we do not need PP stubs in code anymore. After removing it allow us to cleanup and reformat boot code in function predefine_encodings().

Remove PP stubs and reformat predefine_encodings()

---

Unicode/Unicode.pm
lib/Encode/Alias.pm
lib/Encode/Encoding.pm
lib/Encode/Unicode/UTF7.pm

Calling no warnings 'redefine'; just hide a read problem that one function
is later redefined by another. Such thing should not happen, and if there
is it should be fixed.
The real problem is exporting all Encode functions into used modules,
including functions encode() and decode(). Correct way is to export only
those functions which are really needed by modules. Or to call Encode
function with whole package name (e.g. Encode::find_encoding).
Another problem is time when Encode module is loaded. By calling require it
is done at runtime, after current file was already parsed. It is too late
specially for prototyped functions and also constant. Calling use instead
of require fixes this problem.
After those fixes no warnings 'redefine'; can be removed and modules are
warning-free.

Remove no warnings 'redefine'; and correctly load dependences

---

Encode.pm
Makefile.PL

It is not needed to load them conditionally via eval. Encode::MIME::Name is part of Encode and Storable part of Perl since 5.7.3.

Load modules Encode::MIME::Name and Storable normally

---

encoding.pm
lib/Encode/Encoding.pm
t/guess.t

* Add missing comma in usage of encoding pragma description
* In Encode::Encoding initialize DEBUG constant function properly
* In test t/guess.t call use_ok in BEGIN block and remove dead code

Small fixes

---

Encode.xs

* Remove 'eval require Encode::MIME::Name' from Encode::XS code
* Fix memory leak in Encode::XS::mime_name()
* Fix function Encode::XS::renew to not alias input and output value
* Use boolSV instead of newSViv in functions Encode::_utf8_off and Encode::_utf8_on
* Use return value of eval_pv instead of $@ in function Encode::XS::perlio_ok
* Disable prototypes for Encode::XS object methods
* With CODE: directive use void return value only for subroutines which do not return a value and do not set ST(0) directly
* Use PREINIT: directive for variable declarations and INIT: for initial assignment

Fix more XS problems in Encode.xs file

---

lib/Encode/MIME/Header.pm
t/mime-header.t

Encoded quoted-printable text can contain only printable US-ASCII
characters except ?, =, SPACE and TAB. Non-strict mode still allows
non-ASCII characters.
@rjbs please look

Encode::MIME::Header: Fix parsing quoted-printable text in strict mode

---

Makefile.PL

Some gccversion values contain a date, such as "6.3.0 20170516".
Strip that.
Closes #117

Fix gccversion Argument "630 20170516" isn't numeric

---

Encode.pm
MANIFEST
lib/Encode/Alias.pm
t/use-Encode-Alias.t

Calling
use Encode::Alias;
cased error:
Undefined subroutine &Encode::define_alias called at lib/Encode.pm line 102.
Compilation failed in require at lib/Encode/Alias.pm line 7.
BEGIN failed--compilation aborted at lib/Encode/Alias.pm line 7.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
Fixes #116

Fix loading Encode::Alias before Encode

---

Makefile.PL

I only checked the docs for the warning on old gcc's, but
apparently they deviate on -Werror=declaration-after-statement support.
Fixes #113

Fix -Werror=declaration-after-statement for gcc 4.1.2

---

lib/Encode/CN/HZ.pm
lib/Encode/JP/JIS7.pm
lib/Encode/MIME/Header.pm
t/decode.t

* Ensure that encode/decode methods are not called with specified, but undefined check parameter
* Fix warning "Use of uninitialized value $chk in bitwise and (&)" in Encode::MIME::Header::decode()
* For t/decode.t test, set $Test::Builder::Level in croak_ok wrapper

Uninitialized value fixes

---

encoding.pm

In some cases (e.g. when Filter::Util::Call module is not available),
encoding pragma would not work. So caller should get fatal error message
instead of continuous execution of the wrong code.
Fixes: https://rt.cpan.org/Ticket/Display.html?id=100427

Propagate fatal errors from the encoding pragma back to the caller

---

lib/Encode/MIME/Name.pm
t/mime-name.t

LWP::UserAgent [uses IO::HTML](https://github.com/libwww-perl/HTTP-Message/blob/master/lib/HTTP/Message.pm#L242-L250) for determining HTML page's encoding and calls `mime_name()` method of the returned Encode::Encoding object.
This fails with Chinese webpages encoded with GB2312. IO::HTML determined the encoding of said pages to be "euc-cn" but it's not mapped to "EUC-CN" in Encode::MIME::Name and so the subsequent content decoding fails.
To reproduce:
```perl
#!/usr/bin/env perl
use strict;
use warnings;
use v5.10;
use LWP::UserAgent;
my $url = 'https://sandbox.pypt.lt/gb2312.html';
my $ua = LWP::UserAgent->new;
my $response = $ua->get($url);
if ($response->is_success) {
say "Charset: " . $response->content_charset(); # undef; should be "EUC-CN"
say $response->decoded_content();   # …
```

Add "euc-cn" => "EUC-CN" alias to Encode::MIME::Name

---

Encode.pm

Fixes: https://rt.cpan.org/Ticket/Display.html?id=34259

Remove misleading documentation about UTF8 flag

---

Encode.pm

@chansen @khwilliamson can you review this small documentation change?

Include more information about Encode::is_utf8() that it should not be normally used

---

encengine.c

which would end up in an illegal memcmp(NULL, term, tlen).
One could think of malloc dst then, but not for now.

protect do_encode from NULL dst

---

Encode.xs
MANIFEST
t/xml.t

SvPV() macro may return different value as direct access to SV* buffer via
SvPVX() for non-forced scalar. For non-forced scalars SvPV() macro should
be used. Therefore always use only SvPV() family of macros and avoid use of
SvPVX() family (SvCUR, etc...).
Fixes: https://github.com/dankogai/p5-encode/pull/134#issuecomment-458896251

Do not access SV* buffer if we have not called SvPV_force()

---

Encode/encode.h

http://www.cpantesters.org/cpan/report/bd7f4566-52fc-11e9-9066-e374b0ba08e8
http://www.cpantesters.org/cpan/report/04f4c822-563a-11e9-9066-e374b0ba08e8
cc: @khwilliamson this was introduced by your utf8 backport code

Fix linker errors

---

bin/enc2xs

Comment generation in enc2xs can now be suppressed by setting the
ENC2XS_NO_COMMENTS environment variable. This allows enc2xs to produce
reproducible output by omitting the name of the generating program.
Signed-off-by: Joshua Watt <JPEWhacker@gmail.com>

enc2xs: Add environment variable to suppress comments

---

Encode.xs

Fix issue https://github.com/Perl/perl5/issues/17536 and
https://github.com/dankogai/p5-encode/issues/146 and
https://github.com/dankogai/p5-encode/issues/140 and
https://github.com/dankogai/p5-encode/issues/143
Aliasing exposes the 'ix' variable. Since the code does not
change behavior based on the alias (which is what aliases are for)
the functions do not access the 'ix' variable, which throws
warnings. Since Encode is core they need to be fixed.
The correct solution to this is to declare the ix variable
unused by using the PERL_UNUSED_VAR(ix); macro, which
this patch does.

Silence unused var warnings from Encode

---

Encode.pm
Encode.xs

Use the non-deprecated version, which should also work on EBCDIC,
without any extra rigamarole.

Stop using deprecated function

---

Changes
lib/Encode/GSM0338.pm
t/gsm0338.t

* Sort mapping table by UNICODE code points and remove duplicates
* Remove byte 0x1B from mapping table as it is invalid / not defined
* Fix algorithm for decoding:
* Byte 0x00 is not used for escaping in any version of GSM 03.38 standard
* Fix handling of sequence of escape character 0x1B
* Fix bug https://rt.cpan.org/Public/Bug/Display.html?id=124571
* Implement DIE_ON_ERR, WARN_ON_ERR, RETURN_ON_ERR and LEAVE_SRC check flags
* Make this GSM0338 implementation compatible with standards:
* 3GPP TS 23.038 version 16.0.0 Release 16
* ETSI TS 123 038 V16.0.0 (2020-07)
* Update documentation
* Fix spelling ETSI
* Fix UTF-8 vs UNICODE differences
* Add links to normative documents to SEE ALSO section
* Add new section how to handle packed septets
* Add information that this module handles …

GSM0338: Fix encoding module to be compatible with latest GSM 03.38 standard

---

lib/Encode/GSM0338.pm
t/gsm0338.t

Do not decode or throw error when incomplete sequence is on decode input
and STOP_AT_PARTIAL flag was set. This fixes decoding of escaped
(multibyte) GSM characters when they are present at buffer boundary
without need for requiring line buffering.

GSM0338: Enable PerlIO and fix code to not require line buffering

---

Encode.pm

This clarifies why to avoid encode_utf8() and decode_utf8() and expands
on the problem of decoding “utf8”.

Docs updates

---

Unicode/Unicode.xs
t/Unicode_trailing_nul.t

Ensure that UTF-16 decode always includes a trailing NUL.

---

Encode.xs

Pull request https://github.com/dankogai/p5-encode/pull/72 fixed memory
corruption but introduced a new memory leak as dst scalar is not mortal
anymore and not every possible exit from every XS function properly release
scalar's memory.
Fix this memory leak by making dst scalar mortal again. To not re-introduce
that memory corruption, first store dst scalar into temporary variable and
then save it into stack via ST(0) macro.

Fix memory leak in function encode_method()

---

Unicode/Unicode.pm

This link was broken
while I was at it I also updated some other links & references

fix link to Unicode standard

---

t/taint.t

Hi Dan,
I've added a Configure option for building Perl without taint support. If the user selects this, then any taint-related tests need to be skipped. I've made this change in my checkout of blead, but the right way for this to happen is a release of Encode that  is then merged into blead.
This skips the taint tests if your perl was built without taint support.
Cheers,
Neil

Skip taint tests if your perl was built without taint support

---

bin/enc2xs
t/enc_data.t
t/enc_module.t
t/encoding.t
t/jperl.t

This silences the copious warnings produced by modern versions of gcc when compiling with -Wc++-compat. These warnings are bogus as the code actually has different codepaths via defines for C++ and C, so warning about C code that wont compile in C++ is not helpful. 
This also fixes a few other minor nits I noticed when building and testing. 
The Perl issue this fixes is: https://github.com/Perl/perl5/issues/19588
The Encode issues this fixes is: https://github.com/dankogai/p5-encode/issues/144

Fix Issue #144, spurious warnings from -Wc++-compate, and a few related nits

---

lib/Encode/MIME/Header.pm
t/mime-header.t

* Do not allow decoding base64 text with missing padding characters '=' in strict mode.
* Allow missing padding base64 characters in default non-strict mode

Encode::MIME::Header: Fix base64 word decoding

---

t/gsm0338.t

Prior to perl 5.8.8, the :encoding PerlIO layer did not enable STOP_AT_PARTIAL by default. Set it to make sure our test works properly.

fix gsm0338 test compatibility with perl < 5.8.8

---

bin/enc2xs

Fix spelling in comment

---

t/taint.t

If perl is built with -DSILENT_NO_TAINT_SUPPORT checking `$Config{taint_support}` isn't enough, this adds a check that looks for -DSILENT_NO_TAINT_SUPPORT in `$Config{ccflags}`.

Skip taint tests when -DSILENT_NO_TAINT_SUPPORT is enabled.

---

bin/enc2xs

As the indirect object syntax in discouraged

`enc2xs`: Fix indirect syntax

---

Encode.pm

Verbatim sections are rendered ... well, verbatim, so any POD markup (like `I<...>`) will show up in the output as-is (instead of being interpreted as *italics*), which looks ugly. This commit removes such markup from verbatim sections.

remove POD markup from verbatim sections

---

Byte/Makefile.PL

Sort the Encode::Byte byte_t.fnm file output
(and the makefile depends whilst there for good measure).
Otherwise the output is non-deterministic and can change from one build to the next.

Byte/Makefile.PL: ensure build reproducibility
